<a href="https://colab.research.google.com/github/sowntharyakmr-boop/Data-Analysis-using-Python-Project/blob/main/practical_D_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
marks=np.array([90,98,79,60,70])
print(marks[1:4])

[98 79 60]


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
new_arr=arr.reshape(2,3)
print(new_arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
marks = np.array([76,80,90,67])
average = np.mean(marks)
print(average)

78.25


In [ ]:
import numpy as np
salary=np.array([10000,20000,30000,40000,60000])
med=np.median(salary)
print(med)

30000.0


In [ ]:
scores=[85,90,78,95,88]

total=sum(scores)
average=total/len(scores)
highest=max(scores)
lowest=min(scores)

print("Total Score:",total)
print("Average Score:",average)
print("Highest Score:",highest)
print("Lowest Score:",lowest)

Total Score: 436
Average Score: 87.2
Highest Score: 95
Lowest Score: 78


In [ ]:
sales=[1200,1500,1800,2000,1700]
total_sales =sum(sales)
average_sales=total_sales/len(sales)
highest_sales=max(sales)
lowest_sales=min(sales)

print("Total Sales:",total_sales)
print("Average Sales:",average_sales)
print("Highest Sales:",highest_sales)
print("Lowest Sales:",lowest_sales)

Total Sales: 8200
Average Sales: 1640.0
Highest Sales: 2000
Lowest Sales: 1200
